// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "clustergarage.io/janus-controller/pkg/apis/januscontroller/v1alpha1"
	scheme "clustergarage.io/janus-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JanusGuardsGetter has a method to return a JanusGuardInterface.
// A group's client should implement this interface.
type JanusGuardsGetter interface {
	JanusGuards(namespace string) JanusGuardInterface
}

// JanusGuardInterface has methods to work with JanusGuard resources.
type JanusGuardInterface interface {
	Create(*v1alpha1.JanusGuard) (*v1alpha1.JanusGuard, error)
	Update(*v1alpha1.JanusGuard) (*v1alpha1.JanusGuard, error)
	UpdateStatus(*v1alpha1.JanusGuard) (*v1alpha1.JanusGuard, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.JanusGuard, error)
	List(opts v1.ListOptions) (*v1alpha1.JanusGuardList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JanusGuard, err error)
	JanusGuardExpansion
}

// janusGuards implements JanusGuardInterface
type janusGuards struct {
	client rest.Interface
	ns     string
}

// newJanusGuards returns a JanusGuards
func newJanusGuards(c *JanuscontrollerV1alpha1Client, namespace string) *janusGuards {
	return &janusGuards{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the janusGuard, and returns the corresponding janusGuard object, and an error if there is any.
func (c *janusGuards) Get(name string, options v1.GetOptions) (result *v1alpha1.JanusGuard, err error) {
	result = &v1alpha1.JanusGuard{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("janusguards").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of JanusGuards that match those selectors.
func (c *janusGuards) List(opts v1.ListOptions) (result *v1alpha1.JanusGuardList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.JanusGuardList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("janusguards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested janusGuards.
func (c *janusGuards) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("janusguards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a janusGuard and creates it.  Returns the server's representation of the janusGuard, and an error, if there is any.
func (c *janusGuards) Create(janusGuard *v1alpha1.JanusGuard) (result *v1alpha1.JanusGuard, err error) {
	result = &v1alpha1.JanusGuard{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("janusguards").
		Body(janusGuard).
		Do().
		Into(result)
	return
}

// Update takes the representation of a janusGuard and updates it. Returns the server's representation of the janusGuard, and an error, if there is any.
func (c *janusGuards) Update(janusGuard *v1alpha1.JanusGuard) (result *v1alpha1.JanusGuard, err error) {
	result = &v1alpha1.JanusGuard{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("janusguards").
		Name(janusGuard.Name).
		Body(janusGuard).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *janusGuards) UpdateStatus(janusGuard *v1alpha1.JanusGuard) (result *v1alpha1.JanusGuard, err error) {
	result = &v1alpha1.JanusGuard{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("janusguards").
		Name(janusGuard.Name).
		SubResource("status").
		Body(janusGuard).
		Do().
		Into(result)
	return
}

// Delete takes name of the janusGuard and deletes it. Returns an error if one occurs.
func (c *janusGuards) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("janusguards").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *janusGuards) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("janusguards").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched janusGuard.
func (c *janusGuards) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JanusGuard, err error) {
	result = &v1alpha1.JanusGuard{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("janusguards").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
