// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// JanusGuardListerExpansion allows custom methods to be added to
// JanusGuardLister.
type JanusGuardListerExpansion interface{}

// JanusGuardNamespaceListerExpansion allows custom methods to be added to
// JanusGuardNamespaceLister.
type JanusGuardNamespaceListerExpansion interface{}
