// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// JanusWatcherListerExpansion allows custom methods to be added to
// JanusWatcherLister.
type JanusWatcherListerExpansion interface{}

// JanusWatcherNamespaceListerExpansion allows custom methods to be added to
// JanusWatcherNamespaceLister.
type JanusWatcherNamespaceListerExpansion interface{}
