// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	januscontrollerv1alpha1 "clustergarage.io/janus-controller/pkg/apis/januscontroller/v1alpha1"
	versioned "clustergarage.io/janus-controller/pkg/client/clientset/versioned"
	internalinterfaces "clustergarage.io/janus-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "clustergarage.io/janus-controller/pkg/client/listers/januscontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// JanusGuardInformer provides access to a shared informer and lister for
// JanusGuards.
type JanusGuardInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.JanusGuardLister
}

type janusGuardInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewJanusGuardInformer constructs a new informer for JanusGuard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewJanusGuardInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredJanusGuardInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredJanusGuardInformer constructs a new informer for JanusGuard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredJanusGuardInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JanuscontrollerV1alpha1().JanusGuards(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JanuscontrollerV1alpha1().JanusGuards(namespace).Watch(options)
			},
		},
		&januscontrollerv1alpha1.JanusGuard{},
		resyncPeriod,
		indexers,
	)
}

func (f *janusGuardInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredJanusGuardInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *janusGuardInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&januscontrollerv1alpha1.JanusGuard{}, f.defaultInformer)
}

func (f *janusGuardInformer) Lister() v1alpha1.JanusGuardLister {
	return v1alpha1.NewJanusGuardLister(f.Informer().GetIndexer())
}
