// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	januscontrollerv1alpha1 "clustergarage.io/janus-controller/pkg/apis/januscontroller/v1alpha1"
	versioned "clustergarage.io/janus-controller/pkg/client/clientset/versioned"
	internalinterfaces "clustergarage.io/janus-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "clustergarage.io/janus-controller/pkg/client/listers/januscontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// JanusWatcherInformer provides access to a shared informer and lister for
// JanusWatchers.
type JanusWatcherInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.JanusWatcherLister
}

type janusWatcherInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewJanusWatcherInformer constructs a new informer for JanusWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewJanusWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredJanusWatcherInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredJanusWatcherInformer constructs a new informer for JanusWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredJanusWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JanuscontrollerV1alpha1().JanusWatchers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JanuscontrollerV1alpha1().JanusWatchers(namespace).Watch(options)
			},
		},
		&januscontrollerv1alpha1.JanusWatcher{},
		resyncPeriod,
		indexers,
	)
}

func (f *janusWatcherInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredJanusWatcherInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *janusWatcherInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&januscontrollerv1alpha1.JanusWatcher{}, f.defaultInformer)
}

func (f *janusWatcherInformer) Lister() v1alpha1.JanusWatcherLister {
	return v1alpha1.NewJanusWatcherLister(f.Informer().GetIndexer())
}
