// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "clustergarage.io/janus-controller/pkg/apis/januscontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJanusGuards implements JanusGuardInterface
type FakeJanusGuards struct {
	Fake *FakeJanuscontrollerV1alpha1
	ns   string
}

var janusguardsResource = schema.GroupVersionResource{Group: "januscontroller.clustergarage.io", Version: "v1alpha1", Resource: "janusguards"}

var janusguardsKind = schema.GroupVersionKind{Group: "januscontroller.clustergarage.io", Version: "v1alpha1", Kind: "JanusGuard"}

// Get takes name of the janusGuard, and returns the corresponding janusGuard object, and an error if there is any.
func (c *FakeJanusGuards) Get(name string, options v1.GetOptions) (result *v1alpha1.JanusGuard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(janusguardsResource, c.ns, name), &v1alpha1.JanusGuard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JanusGuard), err
}

// List takes label and field selectors, and returns the list of JanusGuards that match those selectors.
func (c *FakeJanusGuards) List(opts v1.ListOptions) (result *v1alpha1.JanusGuardList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(janusguardsResource, janusguardsKind, c.ns, opts), &v1alpha1.JanusGuardList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.JanusGuardList{ListMeta: obj.(*v1alpha1.JanusGuardList).ListMeta}
	for _, item := range obj.(*v1alpha1.JanusGuardList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested janusGuards.
func (c *FakeJanusGuards) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(janusguardsResource, c.ns, opts))

}

// Create takes the representation of a janusGuard and creates it.  Returns the server's representation of the janusGuard, and an error, if there is any.
func (c *FakeJanusGuards) Create(janusGuard *v1alpha1.JanusGuard) (result *v1alpha1.JanusGuard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(janusguardsResource, c.ns, janusGuard), &v1alpha1.JanusGuard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JanusGuard), err
}

// Update takes the representation of a janusGuard and updates it. Returns the server's representation of the janusGuard, and an error, if there is any.
func (c *FakeJanusGuards) Update(janusGuard *v1alpha1.JanusGuard) (result *v1alpha1.JanusGuard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(janusguardsResource, c.ns, janusGuard), &v1alpha1.JanusGuard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JanusGuard), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJanusGuards) UpdateStatus(janusGuard *v1alpha1.JanusGuard) (*v1alpha1.JanusGuard, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(janusguardsResource, "status", c.ns, janusGuard), &v1alpha1.JanusGuard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JanusGuard), err
}

// Delete takes name of the janusGuard and deletes it. Returns an error if one occurs.
func (c *FakeJanusGuards) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(janusguardsResource, c.ns, name), &v1alpha1.JanusGuard{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJanusGuards) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(janusguardsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.JanusGuardList{})
	return err
}

// Patch applies the patch and returns the patched janusGuard.
func (c *FakeJanusGuards) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JanusGuard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(janusguardsResource, c.ns, name, data, subresources...), &v1alpha1.JanusGuard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JanusGuard), err
}
